### PR TITLE
brings upgrades and fixes to linter errors

### LINKED ISSUE #54: Test is always failed
```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/hugomrdias/pull-ws.git
Directory: /Users/ryo/.ghq/github.com/orbitdb/orbit-db-keystore
Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

One of the dependent packages has been renamed and cannot be resolved as a dependency.

`orbit-db-test-utils` -> `ipfs` -> `libp2p-websockets` -> `pull-ws` (this package repository is renamed.)

So we need to update `orbit-db-test-utils` version.

### PR DESCRIPTION
**Pull request by tabcat**
builds on https://github.com/orbitdb/orbit-db-keystore/pull/59 changes

changes made
 - small edits to fix some linter errors
 - upgrades libp2p-crypto to use async api
 - upgrades elliptic package, used for ECC keys
 - upgrades orbit-db-test-utils
 - upgrades orbit-db-storage-adapter

Fixes #54

### CODE REVIEW

File: src/keystore.js [hunk 1]
```diff
@@ -42,20 +46,40 @@ class Keystore {
...
+      await this._upgraded
+    }
+  }
+
   async hasKey (id) {
     if (!id) {
       throw new Error('id needed to check a key')
     }
-    if (this._store.status && this._store.status !== 'open') {
+    if (!this._store || !this._store.isOpen()) {
```
Comment (tabcat) [inline src/keystore.js:73]: thinking about changing this by removing the `!this._store` to match the previous code behavior a bit more

Comment (aphelionz) [reply src/keystore.js:85]: Since our dependencies use optional chaining, requiring us to use node 14+, you could use that here as `!this._store?.isOpen()`

Comment (tabcat) [reply src/keystore.js:85]: we have to revert this change as it messes with the [orbit-db-identity-provider](https://github.com/orbitdb/orbit-db-identity-provider/pull/72) tests

Comment (aphelionz) [reply src/keystore.js:85]: shoot ok
